# Generated by Django 6.0.7 on 2026-07-28 10:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
