# Generated by Django 6.0.7 on 2026-07-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setting', '0005_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
